WITH E AS (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT E.DEPT_ID, D.DEPT_NAME_EN, E.AVG_SAL
FROM E INNER JOIN HR_DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID
ORDER BY AVG_SAL DESC;